Initial Commit
lacework/terraform-aws-ecs-agent pull request #1
Opened 2021-04-13 18:02 UTC by alannix-lw

2021-04-21 23:46 UTC, afiune commented
Oops, that shouldn't have happened. 🤦🏽‍♂️

2021-04-27 23:00 UTC, afiune commented on main.tf
> +  role       = aws_iam_role.ecs_execution[0].name
I think it is better to do this:
```suggestion
  role       = aws_iam_role.ecs_execution[count.index].name
```

2021-04-27 23:01 UTC, afiune commented on main.tf
> +  policy      = data.aws_iam_policy_document.ssm_parameter_store_policy[0].json
same here, what do you think?
```suggestion
  policy      = data.aws_iam_policy_document.ssm_parameter_store_policy[count.index].json
```

2021-04-27 23:02 UTC, afiune commented on main.tf
> +  policy_arn = aws_iam_policy.ssm_parameter_store_policy[0].arn
only if you agree 😅:
```suggestion
  policy_arn = aws_iam_policy.ssm_parameter_store_policy[count.index].arn
```

2021-04-27 23:07 UTC, afiune requested changes
I feel confused with the use of `use_ssm_parameter_store` and `use_existing_ssm_parameter`. I think we should do:
* Enable `use_ssm_parameter_store` to create the SSM parameter OR
* Let the user pass an existing parameter via `use_existing_ssm_parameter`

But not both.

2021-04-28 02:02 UTC, alannix-lw commented
Thanks for the review @afiune - you're the best! Corrected the duplicate effort on having to provide `use_existing_ssm_parameter` and the ARN.

2021-04-28 19:43 UTC, afiune requested changes
One more change and we are gooooood to GO!

2021-04-28 19:43 UTC, afiune commented on README.md
> +| ssm_parameter_arn       | The SSM parameter ARN to use when `use_existing_ssm_parameter` is `true` | `string`      | `""`                       |    no    |
Still see `use_existing_ssm_parameter`

2021-04-28 19:43 UTC, afiune commented on examples/existing-ssm-parameter-kms/README.md
> +  use_existing_ssm_parameter = true
Still see `use_existing_ssm_parameter` here

2021-04-28 19:43 UTC, afiune commented on examples/existing-ssm-parameter/README.md
> +  use_existing_ssm_parameter = true
Still see `use_existing_ssm_parameter` here

2021-04-28 19:43 UTC, afiune commented on variables.tf
> +  description = "The SSM parameter ARN to use when `use_existing_ssm_parameter` is `true`"
Still see `use_existing_ssm_parameter` here

2021-04-28 20:26 UTC, afiune approved these changes
![tenor-130743533](https://user-images.githubusercontent.com/5712253/116468142-bc3c5f80-a82d-11eb-992b-d1058b15b11e.gif)

2021-04-28 20:28 UTC, merged